import type { Team, Player, Match } from "./types"

// Mock Teams Data
export const MOCK_TEAMS: Team[] = [
  // Group A - WITH LOGOS
  {
    id: "team-1",
    team_code: "GREAT_FARCOS_FC",
    name: "Great Farcos FC",
    group: "A",
    isAS1Team: true,
    description: "AS1 Elite Academy Team",
    logoUrl: "/teams/GREAT_FARCOS_FC_A.png",
  },
  {
    id: "team-2",
    team_code: "ATTRAM_DE_VISSER",
    name: "Attram De Visser",
    group: "A",
    isAS1Team: false,
    logoUrl: "/teams/ATTRAM_DE_VISSER_A.png",
  },
  {
    id: "team-3",
    team_code: "DWISE_XI",
    name: "Dwise XI",
    group: "A",
    isAS1Team: false,
    logoUrl: "/teams/DWISE_XI_A.png",
  },
  {
    id: "team-4",
    team_code: "JEK_FC",
    name: "JEK FC",
    group: "A",
    isAS1Team: false,
    logoUrl: "/teams/JEK_FC_A.png",
  },
  {
    id: "team-5",
    team_code: "SOAR_ACADEMY",
    name: "Soar Academy",
    group: "A",
    isAS1Team: false,
    logoUrl: "/teams/SOAR_ACADEMY_A.png",
  },
  // Group B - WITHOUT LOGOS (for comparison)
  {
    id: "team-6",
    team_code: "AS1_ACADEMY_ELITE",
    name: "AS1 Academy Elite",
    group: "B",
    isAS1Team: true,
    description: "AS1 Premier Development Squad",
  },
  {
    id: "team-7",
    team_code: "SEVILLA_FC",
    name: "Sevilla FC",
    group: "B",
    isAS1Team: false,
  },
  {
    id: "team-8",
    team_code: "ATHLETIC_BILBAO",
    name: "Athletic Bilbao",
    group: "B",
    isAS1Team: false,
  },
  {
    id: "team-9",
    team_code: "REAL_SOCIEDAD",
    name: "Real Sociedad",
    group: "B",
    isAS1Team: false,
  },
  {
    id: "team-10",
    team_code: "VILLARREAL_CF",
    name: "Villarreal CF",
    group: "B",
    isAS1Team: false,
  },
]

// Mock Players Data
export const MOCK_PLAYERS: Player[] = [
  // Great Farcos FC (Team 1)
  {
    id: "player-1",
    firstName: "Carlos",
    lastName: "Rodriguez",
    jerseyNumber: 10,
    position: "Forward",
    teamId: "team-1",
    birthDate: "2005-03-15",
    height: 178,
    weight: 72,
    nationality: "Spain",
    dominantFoot: "right",
    photoUrl: "/young-soccer-player-portrait.png",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    stats: {
      gamesPlayed: 12,
      goals: 8,
      assists: 5,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 980,
    },
  },
  {
    id: "player-2",
    firstName: "Miguel",
    lastName: "Santos",
    jerseyNumber: 7,
    position: "Midfielder",
    teamId: "team-1",
    birthDate: "2006-07-22",
    height: 175,
    weight: 68,
    nationality: "Spain",
    dominantFoot: "left",
    stats: {
      gamesPlayed: 11,
      goals: 3,
      assists: 7,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 890,
    },
  },
  {
    id: "player-3",
    firstName: "David",
    lastName: "Martinez",
    jerseyNumber: 4,
    position: "Defender",
    teamId: "team-1",
    birthDate: "2005-11-08",
    height: 182,
    weight: 76,
    nationality: "Spain",
    dominantFoot: "right",
    photoUrl: "/soccer-defender-portrait.jpg",
    videoUrl: "https://www.youtube.com/watch?v=9bZkp7q19f0",
    stats: {
      gamesPlayed: 12,
      goals: 1,
      assists: 2,
      yellowCards: 3,
      redCards: 0,
      minutesPlayed: 1080,
    },
  },
  // Atletico Madrid (Team 2)
  {
    id: "player-4",
    firstName: "Lucas",
    lastName: "Fernandez",
    jerseyNumber: 9,
    position: "Forward",
    teamId: "team-2",
    birthDate: "2005-05-12",
    height: 180,
    weight: 74,
    nationality: "Spain",
    dominantFoot: "both",
    stats: {
      gamesPlayed: 10,
      goals: 6,
      assists: 3,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 850,
    },
  },
  {
    id: "player-5",
    firstName: "Pablo",
    lastName: "Garcia",
    jerseyNumber: 8,
    position: "Midfielder",
    teamId: "team-2",
    birthDate: "2006-02-18",
    height: 176,
    weight: 70,
    nationality: "Spain",
    photoUrl: "/young-midfielder-soccer.jpg",
    videoUrl: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
    stats: {
      gamesPlayed: 11,
      goals: 4,
      assists: 6,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 920,
    },
  },
  // Real Madrid (Team 3)
  {
    id: "player-6",
    firstName: "Javier",
    lastName: "Lopez",
    jerseyNumber: 11,
    position: "Forward",
    teamId: "team-3",
    birthDate: "2005-09-25",
    height: 177,
    weight: 71,
    nationality: "Spain",
    photoUrl: "/soccer-striker-portrait.jpg",
    stats: {
      gamesPlayed: 12,
      goals: 9,
      assists: 4,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 1020,
    },
  },
  {
    id: "player-7",
    firstName: "Antonio",
    lastName: "Ruiz",
    jerseyNumber: 6,
    position: "Midfielder",
    teamId: "team-3",
    birthDate: "2006-04-30",
    height: 174,
    weight: 67,
    nationality: "Spain",
    stats: {
      gamesPlayed: 11,
      goals: 2,
      assists: 8,
      yellowCards: 0,
      redCards: 0,
      minutesPlayed: 950,
    },
  },
  // Barcelona FC (Team 4)
  // JEK FC (Team 4) - Real Data
  {
    id: "player-8",
    firstName: "MORY WILLIAMS",
    lastName: "DIOMANDE",
    jerseyNumber: 16,
    position: "GoalKeeper",
    teamId: "team-4",
    birthDate: "2007-10-31",
    height: 177,
    weight: 70,
    dominantFoot: "right",
    photoUrl: "/players/JEK_FC_16.jpg",
    stats: {
      gamesPlayed: 8,
      goals: 0,
      assists: 0,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 720,
    },
  },
  {
    id: "player-9",
    firstName: "CHEICK KADER",
    lastName: "OUATTARA",
    jerseyNumber: 30,
    position: "GoalKeeper",
    teamId: "team-4",
    birthDate: "2010-03-16",
    height: 182,
    weight: 75,
    dominantFoot: "right",
    photoUrl: "/players/JEK_FC_30.jpg",
    stats: {
      gamesPlayed: 6,
      goals: 0,
      assists: 0,
      yellowCards: 0,
      redCards: 0,
      minutesPlayed: 540,
    },
  },
  {
    id: "player-10",
    firstName: "ADAM",
    lastName: "SAMOURA",
    jerseyNumber: 2,
    position: "Central back",
    teamId: "team-4",
    birthDate: "2008-10-21",
    height: 177,
    weight: 72,
    dominantFoot: "right",
    photoUrl: "/players/JEK_FC_2.jpg",
    stats: {
      gamesPlayed: 10,
      goals: 1,
      assists: 0,
      yellowCards: 3,
      redCards: 0,
      minutesPlayed: 900,
    },
  },
  {
    id: "player-11",
    firstName: "FOUSSENY",
    lastName: "BAMBA",
    jerseyNumber: 3,
    position: "Left back",
    teamId: "team-4",
    birthDate: "2008-10-30",
    height: 177,
    weight: 71,
    dominantFoot: "left",
    photoUrl: "/players/JEK_FC_3.jpg",
    stats: {
      gamesPlayed: 9,
      goals: 0,
      assists: 2,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 810,
    },
  },
  {
    id: "player-12",
    firstName: "FRANCK SYLVA",
    lastName: "KOKOLOU",
    jerseyNumber: 6,
    position: "Central back",
    teamId: "team-4",
    birthDate: "2008-07-13",
    height: 177,
    weight: 73,
    dominantFoot: "right",
    photoUrl: "/players/JEK_FC_6.jpg",
    stats: {
      gamesPlayed: 11,
      goals: 0,
      assists: 1,
      yellowCards: 4,
      redCards: 0,
      minutesPlayed: 990,
    },
  },
  {
    id: "player-13",
    firstName: "ANGE MICKAEL",
    lastName: "KOUASSI",
    jerseyNumber: 13,
    position: "Left back",
    teamId: "team-4",
    birthDate: "2010-11-24",
    height: 175,
    weight: 68,
    dominantFoot: "left",
    photoUrl: "/players/JEK_FC_13.jpg",
    stats: {
      gamesPlayed: 7,
      goals: 0,
      assists: 1,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 630,
    },
  },
  {
    id: "player-14",
    firstName: "KADER MOHAMED",
    lastName: "DOSSO",
    jerseyNumber: 22,
    position: "Right Back",
    teamId: "team-4",
    birthDate: "2009-10-31",
    height: 169,
    weight: 65,
    dominantFoot: "right",
    photoUrl: "/players/JEK_FC_22.jpg",
    stats: {
      gamesPlayed: 8,
      goals: 0,
      assists: 3,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 720,
    },
  },
  {
    id: "player-15",
    firstName: "OULAI ELIE",
    lastName: "SOUHA",
    jerseyNumber: 25,
    position: "Central back",
    teamId: "team-4",
    birthDate: "2009-05-02",
    height: 181,
    weight: 76,
    dominantFoot: "right",
    photoUrl: "/players/JEK_FC_25.jpg",
    stats: {
      gamesPlayed: 10,
      goals: 1,
      assists: 0,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 900,
    },
  },
  {
    id: "player-16",
    firstName: "CHEICK RAHIMI",
    lastName: "COULIBALY",
    jerseyNumber: 32,
    position: "Central back",
    teamId: "team-4",
    birthDate: "2010-01-08",
    height: 177,
    weight: 72,
    dominantFoot: "right",
    photoUrl: "/players/JEK_FC_32.jpg",
    stats: {
      gamesPlayed: 6,
      goals: 0,
      assists: 0,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 540,
    },
  },
  {
    id: "player-17",
    firstName: "ALEX",
    lastName: "CUDJOE",
    jerseyNumber: 33,
    position: "Right Back",
    teamId: "team-4",
    birthDate: "2007-01-02",
    height: 172,
    weight: 69,
    dominantFoot: "right",
    photoUrl: "/players/JEK_FC_33.jpg",
    stats: {
      gamesPlayed: 12,
      goals: 0,
      assists: 4,
      yellowCards: 3,
      redCards: 0,
      minutesPlayed: 1080,
    },
  },
  {
    id: "player-18",
    firstName: "KOUASSI CHRIST",
    lastName: "KOFFI",
    jerseyNumber: 5,
    position: "Defensive midfielder",
    teamId: "team-4",
    birthDate: "2009-10-31",
    height: 170,
    weight: 67,
    dominantFoot: "right",
    stats: {
      gamesPlayed: 9,
      goals: 2,
      assists: 1,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 810,
    },
  },
  {
    id: "player-19",
    firstName: "ASSEMIEN PAUL",
    lastName: "KADIO",
    jerseyNumber: 8,
    position: "Midfielder",
    teamId: "team-4",
    birthDate: "2009-04-06",
    height: 170,
    weight: 68,
    dominantFoot: "right",
    stats: {
      gamesPlayed: 11,
      goals: 3,
      assists: 5,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 990,
    },
  },
  {
    id: "player-20",
    firstName: "YAO CEDRIC ARMEL",
    lastName: "KOFFI",
    jerseyNumber: 10,
    position: "Midfielder",
    teamId: "team-4",
    birthDate: "2009-08-30",
    height: 172,
    weight: 69,
    dominantFoot: "right",
    stats: {
      gamesPlayed: 10,
      goals: 4,
      assists: 6,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 900,
    },
  },
  {
    id: "player-21",
    firstName: "THEOPHILUS",
    lastName: "KUMA",
    jerseyNumber: 12,
    position: "Midfielder",
    teamId: "team-4",
    birthDate: "2009-03-13",
    height: 167,
    weight: 64,
    dominantFoot: "left",
    stats: {
      gamesPlayed: 8,
      goals: 2,
      assists: 3,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 720,
    },
  },
  {
    id: "player-22",
    firstName: "SEYDOU",
    lastName: "COULIBALY",
    jerseyNumber: 17,
    position: "Defensive midfielder",
    teamId: "team-4",
    birthDate: "2008-10-27",
    height: 174,
    weight: 70,
    dominantFoot: "left",
    stats: {
      gamesPlayed: 9,
      goals: 1,
      assists: 2,
      yellowCards: 3,
      redCards: 0,
      minutesPlayed: 810,
    },
  },
  {
    id: "player-23",
    firstName: "BAKARY N'DOKOLIO",
    lastName: "COULIBALY",
    jerseyNumber: 27,
    position: "Defensive midfielder",
    teamId: "team-4",
    birthDate: "2008-12-12",
    height: 164,
    weight: 62,
    dominantFoot: "right",
    stats: {
      gamesPlayed: 7,
      goals: 0,
      assists: 1,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 630,
    },
  },
  {
    id: "player-24",
    firstName: "CHEICK",
    lastName: "SAWADOGO",
    jerseyNumber: 7,
    position: "Winger",
    teamId: "team-4",
    birthDate: "2009-12-16",
    height: 177,
    weight: 71,
    dominantFoot: "right",
    stats: {
      gamesPlayed: 10,
      goals: 5,
      assists: 4,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 900,
    },
  },
  {
    id: "player-25",
    firstName: "IBRAHIM",
    lastName: "TRAORE",
    jerseyNumber: 9,
    position: "Striker",
    teamId: "team-4",
    birthDate: "2007-11-02",
    height: 176,
    weight: 73,
    dominantFoot: "right",
    stats: {
      gamesPlayed: 12,
      goals: 8,
      assists: 2,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 1080,
    },
  },
  {
    id: "player-26",
    firstName: "KASSOUM MESSI",
    lastName: "DIOMANDE",
    jerseyNumber: 15,
    position: "Winger",
    teamId: "team-4",
    birthDate: "2007-12-05",
    height: 177,
    weight: 72,
    dominantFoot: "right",
    stats: {
      gamesPlayed: 11,
      goals: 6,
      assists: 5,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 990,
    },
  },
  {
    id: "player-27",
    firstName: "SINA",
    lastName: "SOUMARE",
    jerseyNumber: 19,
    position: "Winger",
    teamId: "team-4",
    birthDate: "2008-08-31",
    height: 163,
    weight: 61,
    dominantFoot: "right",
    stats: {
      gamesPlayed: 9,
      goals: 3,
      assists: 3,
      yellowCards: 0,
      redCards: 0,
      minutesPlayed: 810,
    },
  },
  {
    id: "player-28",
    firstName: "ABDOUL",
    lastName: "BAMBA",
    jerseyNumber: 28,
    position: "Striker",
    teamId: "team-4",
    birthDate: "2007-10-31",
    height: 179,
    weight: 75,
    dominantFoot: "right",
    stats: {
      gamesPlayed: 10,
      goals: 7,
      assists: 1,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 900,
    },
  },
  {
    id: "player-29",
    firstName: "LOUIS MICHEL",
    lastName: "BRITON",
    jerseyNumber: 29,
    position: "Winger",
    teamId: "team-4",
    birthDate: "2009-02-03",
    height: 194,
    weight: 85,
    dominantFoot: "left",
    stats: {
      gamesPlayed: 8,
      goals: 4,
      assists: 2,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 720,
    },
  },
  // AS1 Academy Elite (Team 6)
  {
    id: "player-10",
    firstName: "Marco",
    lastName: "Silva",
    jerseyNumber: 9,
    position: "Forward",
    teamId: "team-6",
    birthDate: "2005-08-20",
    height: 181,
    weight: 75,
    nationality: "Portugal",
    photoUrl: "/portuguese-soccer-forward.jpg",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    stats: {
      gamesPlayed: 11,
      goals: 7,
      assists: 4,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 940,
    },
  },
  {
    id: "player-11",
    firstName: "Andre",
    lastName: "Costa",
    jerseyNumber: 7,
    position: "Midfielder",
    teamId: "team-6",
    birthDate: "2006-01-10",
    height: 173,
    weight: 66,
    nationality: "Portugal",
    photoUrl: "/young-midfielder-soccer.jpg",
    videoUrl: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
    stats: {
      gamesPlayed: 12,
      goals: 5,
      assists: 9,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 1010,
    },
  },
  {
    id: "player-12",
    firstName: "Bruno",
    lastName: "Alves",
    jerseyNumber: 3,
    position: "Defender",
    teamId: "team-6",
    birthDate: "2005-10-05",
    height: 184,
    weight: 78,
    nationality: "Portugal",
    photoUrl: "/soccer-defender-portrait.jpg",
    videoUrl: "https://www.youtube.com/watch?v=9bZkp7q19f0",
    stats: {
      gamesPlayed: 12,
      goals: 1,
      assists: 0,
      yellowCards: 3,
      redCards: 0,
      minutesPlayed: 1080,
    },
  },
]

// Mock Matches Data
export const MOCK_MATCHES: Match[] = [
  {
    id: "match-1",
    homeTeamId: "team-1",
    awayTeamId: "team-2",
    date: "2025-01-15",
    time: "18:00",
    venue: "AS1 Stadium",
    videoProvider: "youtube",
    status: "finished",
    score: {
      home: 2,
      away: 1,
    },
  },
  {
    id: "match-2",
    homeTeamId: "team-3",
    awayTeamId: "team-4",
    date: "2025-01-15",
    time: "20:00",
    venue: "Santiago Bernabeu",
    videoProvider: "veo",
    status: "finished",
    score: {
      home: 3,
      away: 3,
    },
  },
  {
    id: "match-3",
    homeTeamId: "team-6",
    awayTeamId: "team-7",
    date: "2025-01-16",
    time: "17:00",
    venue: "AS1 Training Ground",
    videoProvider: "youtube",
    status: "finished",
    score: {
      home: 1,
      away: 0,
    },
  },
  {
    id: "match-4",
    homeTeamId: "team-2",
    awayTeamId: "team-5",
    date: "2025-01-20",
    time: "19:00",
    venue: "Wanda Metropolitano",
    status: "scheduled",
  },
  {
    id: "match-5",
    homeTeamId: "team-1",
    awayTeamId: "team-3",
    date: "2025-01-22",
    time: "18:30",
    venue: "AS1 Stadium",
    status: "scheduled",
  },
  {
    id: "match-6",
    homeTeamId: "team-8",
    awayTeamId: "team-6",
    date: "2025-01-23",
    time: "20:00",
    venue: "San Mames",
    status: "scheduled",
  },
  // Group A Matches - Real Data
  {
    id: "match-group-a-1",
    homeTeamId: "team-4", // JEK_FC
    awayTeamId: "team-2", // ATTRAM_DE_VISSER
    date: "2025-10-21",
    time: "08:15",
    venue: "AS1 Stadium",
    videoProvider: "youtube",
    status: "scheduled",
  },
  {
    id: "match-group-a-2",
    homeTeamId: "team-3", // DWISE_XI
    awayTeamId: "team-1", // GREAT_FARCOS_FC
    date: "2025-10-21",
    time: "09:45",
    venue: "AS1 Stadium",
    videoProvider: "youtube",
    status: "scheduled",
  },
  {
    id: "match-group-a-3",
    homeTeamId: "team-3", // DWISE_XI
    awayTeamId: "team-4", // JEK_FC
    date: "2025-10-22",
    time: "08:15",
    venue: "AS1 Stadium",
    videoProvider: "youtube",
    status: "scheduled",
  },
  {
    id: "match-group-a-4",
    homeTeamId: "team-2", // ATTRAM_DE_VISSER
    awayTeamId: "team-1", // GREAT_FARCOS_FC
    date: "2025-10-22",
    time: "09:45",
    venue: "AS1 Stadium",
    videoProvider: "youtube",
    status: "scheduled",
  },
  {
    id: "match-group-a-5",
    homeTeamId: "team-1", // GREAT_FARCOS_FC
    awayTeamId: "team-4", // JEK_FC
    date: "2025-10-23",
    time: "08:15",
    venue: "AS1 Stadium",
    videoProvider: "youtube",
    status: "scheduled",
  },
  {
    id: "match-group-a-6",
    homeTeamId: "team-2", // ATTRAM_DE_VISSER
    awayTeamId: "team-3", // DWISE_XI
    date: "2025-10-23",
    time: "09:45",
    venue: "AS1 Stadium",
    videoProvider: "youtube",
    status: "scheduled",
  },
]

// Helper functions
export function getTeamById(teamId: string): Team | undefined {
  return MOCK_TEAMS.find((t) => t.id === teamId)
}

export function getPlayersByTeam(teamId: string): Player[] {
  return MOCK_PLAYERS.filter((p) => p.teamId === teamId)
}

export function getPlayerById(playerId: string): Player | undefined {
  return MOCK_PLAYERS.find((p) => p.id === playerId)
}

export function getTeamsByGroup(group: "A" | "B"): Team[] {
  return MOCK_TEAMS.filter((t) => t.group === group)
}

export function getMatchesByTeam(teamId: string): Match[] {
  return MOCK_MATCHES.filter((m) => m.homeTeamId === teamId || m.awayTeamId === teamId)
}
