import type { Team, Player, Match } from "./types"

// Mock Teams Data
export const MOCK_TEAMS: Team[] = [
  // Group A - WITH LOGOS
  {
    id: "team-1",
    name: "Great Farcos FC",
    group: "A",
    isAS1Team: true,
    description: "AS1 Elite Academy Team",
    logoUrl: "/teams/as1-logo.jpg",
  },
  {
    id: "team-2",
    name: "Atletico Madrid",
    group: "A",
    isAS1Team: false,
    logoUrl: "/teams/atletico-madrid-logo.jpg",
  },
  {
    id: "team-3",
    name: "Real Madrid",
    group: "A",
    isAS1Team: false,
    logoUrl: "/teams/real-madrid-logo.jpg",
  },
  {
    id: "team-4",
    name: "Barcelona FC",
    group: "A",
    isAS1Team: false,
    logoUrl: "/teams/barcelona-logo.jpg",
  },
  {
    id: "team-5",
    name: "Valencia CF",
    group: "A",
    isAS1Team: false,
    logoUrl: "/teams/valencia-logo.jpg",
  },
  // Group B - WITHOUT LOGOS (for comparison)
  {
    id: "team-6",
    name: "AS1 Academy Elite",
    group: "B",
    isAS1Team: true,
    description: "AS1 Premier Development Squad",
  },
  {
    id: "team-7",
    name: "Sevilla FC",
    group: "B",
    isAS1Team: false,
  },
  {
    id: "team-8",
    name: "Athletic Bilbao",
    group: "B",
    isAS1Team: false,
  },
  {
    id: "team-9",
    name: "Real Sociedad",
    group: "B",
    isAS1Team: false,
  },
  {
    id: "team-10",
    name: "Villarreal CF",
    group: "B",
    isAS1Team: false,
  },
]

// Mock Players Data
export const MOCK_PLAYERS: Player[] = [
  // Great Farcos FC (Team 1)
  {
    id: "player-1",
    firstName: "Carlos",
    lastName: "Rodriguez",
    jerseyNumber: 10,
    position: "Forward",
    teamId: "team-1",
    birthDate: "2005-03-15",
    height: 178,
    weight: 72,
    nationality: "Spain",
    photoUrl: "/young-soccer-player-portrait.png",
    videoUrls: ["https://www.youtube.com/watch?v=dQw4w9WgXcQ", "https://www.youtube.com/watch?v=jNQXAC9IVRw"],
    stats: {
      gamesPlayed: 12,
      goals: 8,
      assists: 5,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 980,
    },
  },
  {
    id: "player-2",
    firstName: "Miguel",
    lastName: "Santos",
    jerseyNumber: 7,
    position: "Midfielder",
    teamId: "team-1",
    birthDate: "2006-07-22",
    height: 175,
    weight: 68,
    nationality: "Spain",
    stats: {
      gamesPlayed: 11,
      goals: 3,
      assists: 7,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 890,
    },
  },
  {
    id: "player-3",
    firstName: "David",
    lastName: "Martinez",
    jerseyNumber: 4,
    position: "Defender",
    teamId: "team-1",
    birthDate: "2005-11-08",
    height: 182,
    weight: 76,
    nationality: "Spain",
    photoUrl: "/soccer-defender-portrait.jpg",
    videoUrls: ["https://www.youtube.com/watch?v=9bZkp7q19f0"],
    stats: {
      gamesPlayed: 12,
      goals: 1,
      assists: 2,
      yellowCards: 3,
      redCards: 0,
      minutesPlayed: 1080,
    },
  },
  // Atletico Madrid (Team 2)
  {
    id: "player-4",
    firstName: "Lucas",
    lastName: "Fernandez",
    jerseyNumber: 9,
    position: "Forward",
    teamId: "team-2",
    birthDate: "2005-05-12",
    height: 180,
    weight: 74,
    nationality: "Spain",
    stats: {
      gamesPlayed: 10,
      goals: 6,
      assists: 3,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 850,
    },
  },
  {
    id: "player-5",
    firstName: "Pablo",
    lastName: "Garcia",
    jerseyNumber: 8,
    position: "Midfielder",
    teamId: "team-2",
    birthDate: "2006-02-18",
    height: 176,
    weight: 70,
    nationality: "Spain",
    photoUrl: "/young-midfielder-soccer.jpg",
    videoUrls: [
      "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
      "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
      "https://www.youtube.com/watch?v=60ItHLz5WEA",
    ],
    stats: {
      gamesPlayed: 11,
      goals: 4,
      assists: 6,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 920,
    },
  },
  // Real Madrid (Team 3)
  {
    id: "player-6",
    firstName: "Javier",
    lastName: "Lopez",
    jerseyNumber: 11,
    position: "Forward",
    teamId: "team-3",
    birthDate: "2005-09-25",
    height: 177,
    weight: 71,
    nationality: "Spain",
    photoUrl: "/soccer-striker-portrait.jpg",
    stats: {
      gamesPlayed: 12,
      goals: 9,
      assists: 4,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 1020,
    },
  },
  {
    id: "player-7",
    firstName: "Antonio",
    lastName: "Ruiz",
    jerseyNumber: 6,
    position: "Midfielder",
    teamId: "team-3",
    birthDate: "2006-04-30",
    height: 174,
    weight: 67,
    nationality: "Spain",
    stats: {
      gamesPlayed: 11,
      goals: 2,
      assists: 8,
      yellowCards: 0,
      redCards: 0,
      minutesPlayed: 950,
    },
  },
  // Barcelona FC (Team 4)
  {
    id: "player-8",
    firstName: "Sergio",
    lastName: "Morales",
    jerseyNumber: 10,
    position: "Forward",
    teamId: "team-4",
    birthDate: "2005-06-14",
    height: 179,
    weight: 73,
    nationality: "Spain",
    stats: {
      gamesPlayed: 12,
      goals: 10,
      assists: 6,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 1050,
    },
  },
  {
    id: "player-9",
    firstName: "Rafael",
    lastName: "Diaz",
    jerseyNumber: 5,
    position: "Defender",
    teamId: "team-4",
    birthDate: "2005-12-03",
    height: 183,
    weight: 77,
    nationality: "Spain",
    photoUrl: "/soccer-center-back.jpg",
    stats: {
      gamesPlayed: 12,
      goals: 0,
      assists: 1,
      yellowCards: 4,
      redCards: 1,
      minutesPlayed: 1000,
    },
  },
  // AS1 Academy Elite (Team 6)
  {
    id: "player-10",
    firstName: "Marco",
    lastName: "Silva",
    jerseyNumber: 9,
    position: "Forward",
    teamId: "team-6",
    birthDate: "2005-08-20",
    height: 181,
    weight: 75,
    nationality: "Portugal",
    photoUrl: "/portuguese-soccer-forward.jpg",
    videoUrls: ["https://www.youtube.com/watch?v=dQw4w9WgXcQ", "https://www.youtube.com/watch?v=jNQXAC9IVRw"],
    stats: {
      gamesPlayed: 11,
      goals: 7,
      assists: 4,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 940,
    },
  },
  {
    id: "player-11",
    firstName: "Andre",
    lastName: "Costa",
    jerseyNumber: 7,
    position: "Midfielder",
    teamId: "team-6",
    birthDate: "2006-01-10",
    height: 173,
    weight: 66,
    nationality: "Portugal",
    photoUrl: "/young-midfielder-soccer.jpg",
    videoUrls: [
      "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
      "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
      "https://www.youtube.com/watch?v=60ItHLz5WEA",
    ],
    stats: {
      gamesPlayed: 12,
      goals: 5,
      assists: 9,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 1010,
    },
  },
  {
    id: "player-12",
    firstName: "Bruno",
    lastName: "Alves",
    jerseyNumber: 3,
    position: "Defender",
    teamId: "team-6",
    birthDate: "2005-10-05",
    height: 184,
    weight: 78,
    nationality: "Portugal",
    photoUrl: "/soccer-defender-portrait.jpg",
    videoUrls: ["https://www.youtube.com/watch?v=9bZkp7q19f0"],
    stats: {
      gamesPlayed: 12,
      goals: 1,
      assists: 0,
      yellowCards: 3,
      redCards: 0,
      minutesPlayed: 1080,
    },
  },
]

// Mock Matches Data
export const MOCK_MATCHES: Match[] = [
  {
    id: "match-1",
    homeTeamId: "team-1",
    awayTeamId: "team-2",
    date: "2025-01-15",
    time: "18:00",
    venue: "AS1 Stadium",
    videoProvider: "youtube",
    status: "finished",
    score: {
      home: 2,
      away: 1,
    },
  },
  {
    id: "match-2",
    homeTeamId: "team-3",
    awayTeamId: "team-4",
    date: "2025-01-15",
    time: "20:00",
    venue: "Santiago Bernabeu",
    videoProvider: "veo",
    status: "finished",
    score: {
      home: 3,
      away: 3,
    },
  },
  {
    id: "match-3",
    homeTeamId: "team-6",
    awayTeamId: "team-7",
    date: "2025-01-16",
    time: "17:00",
    venue: "AS1 Training Ground",
    videoProvider: "youtube",
    status: "finished",
    score: {
      home: 1,
      away: 0,
    },
  },
  {
    id: "match-4",
    homeTeamId: "team-2",
    awayTeamId: "team-5",
    date: "2025-01-20",
    time: "19:00",
    venue: "Wanda Metropolitano",
    status: "scheduled",
  },
  {
    id: "match-5",
    homeTeamId: "team-1",
    awayTeamId: "team-3",
    date: "2025-01-22",
    time: "18:30",
    venue: "AS1 Stadium",
    status: "scheduled",
  },
  {
    id: "match-6",
    homeTeamId: "team-8",
    awayTeamId: "team-6",
    date: "2025-01-23",
    time: "20:00",
    venue: "San Mames",
    status: "scheduled",
  },
]

// Helper functions
export function getTeamById(teamId: string): Team | undefined {
  return MOCK_TEAMS.find((t) => t.id === teamId)
}

export function getPlayersByTeam(teamId: string): Player[] {
  return MOCK_PLAYERS.filter((p) => p.teamId === teamId)
}

export function getPlayerById(playerId: string): Player | undefined {
  return MOCK_PLAYERS.find((p) => p.id === playerId)
}

export function getTeamsByGroup(group: "A" | "B"): Team[] {
  return MOCK_TEAMS.filter((t) => t.group === group)
}

export function getMatchesByTeam(teamId: string): Match[] {
  return MOCK_MATCHES.filter((m) => m.homeTeamId === teamId || m.awayTeamId === teamId)
}
