export const PLAYER_STATS_TEXTS = {
  UI: {
    TITLE: "Performance Stats",
    LOADING_MESSAGE: "Loading player statistics...",
    ERROR_MESSAGE: "Error loading statistics:",
    NO_STATS_MESSAGE: "No statistics available for this player",
    NO_STATS_CONTAINER: "p-6",
    NO_STATS_MESSAGE_CLASSES: "text-muted-foreground text-center",
    CARD: {
      TITLE_CLASSES: "flex items-center gap-2",
      ICON: "📊",
    },
    RESPONSIVE: {
      MOBILE_HIDDEN: "hidden md:block",
      DESKTOP_HIDDEN: "block md:hidden",
    },
    MOBILE_NAVIGATION: {
      PREVIOUS: "Previous category",
      NEXT: "Next category",
      CATEGORY_COUNTER: (current: number, total: number) => `${current} of ${total}`,
    },
    MOBILE: {
      NAVIGATION_CONTAINER: "flex items-center justify-between mb-6",
      BUTTON_CLASSES: "h-10 w-10 p-0 rounded-full shadow-sm hover:shadow-md transition-all duration-200 disabled:opacity-50",
      CATEGORY_DISPLAY: "flex-1 mx-4",
      CATEGORY_CARD: "text-center p-4 rounded-xl bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-800 dark:to-slate-900 border border-slate-200 dark:border-slate-700 shadow-sm",
      CATEGORY_HEADER: "flex items-center justify-center gap-3 mb-2",
      CATEGORY_ICON_CONTAINER: "p-2 rounded-lg bg-white dark:bg-slate-700 shadow-sm",
      CATEGORY_NAME: "font-semibold text-base",
      CATEGORY_COUNTER: "text-xs text-muted-foreground font-medium",
      INDICATORS_CONTAINER: "flex justify-center gap-2 mb-6",
      INDICATOR_BUTTON: "w-2 h-2 rounded-full transition-all duration-200",
      INDICATOR_ACTIVE: "bg-slate-600 dark:bg-slate-400",
      INDICATOR_INACTIVE: "bg-slate-300 dark:bg-slate-600",
      CATEGORY_ICON_CLASSES: "h-5 w-5",
    },
    TABS: {
      CONTAINER_CLASSES: "overflow-x-auto pb-2",
      LIST_CLASSES: "inline-flex w-max min-w-full justify-start space-x-2 p-1 bg-slate-50 dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-700",
      TRIGGER_CLASSES: "flex items-center gap-2 px-4 py-2.5 text-xs sm:text-sm whitespace-nowrap min-w-0 transition-all duration-300 rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm data-[state=active]:border data-[state=active]:border-slate-200 dark:data-[state=active]:bg-slate-800 dark:data-[state=active]:border-slate-600 hover:bg-white/50 dark:hover:bg-slate-800/50",
      CONTENT_CLASSES: "mt-6",
      TRIGGER_ICON_CLASSES: "h-4 w-4 sm:h-5 sm:w-5 flex-shrink-0",
      TRIGGER_TEXT_CLASSES: "hidden xs:inline sm:inline truncate font-medium",
    },
    CATEGORY_CONTENT: {
      GRID_CLASSES: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-4",
      CARD_CLASSES: "flex flex-col",
      CARD_CONTENT_CLASSES: "p-3 sm:p-4 flex-1 flex flex-col justify-between",
      METRIC_HEADER: "flex items-center gap-2 mb-1",
      METRIC_NAME: "text-xs sm:text-sm font-medium text-muted-foreground",
      METRIC_VALUE: "text-sm sm:text-lg font-semibold leading-tight",
      METRIC_DISPLAY: "mt-2 sm:mt-3",
      METRIC_NUMBER: "text-xl sm:text-2xl font-bold text-foreground",
      METRIC_ICON_CLASSES: "h-3 w-3 sm:h-4 sm:w-4",
    },
  },
  PERFORMANCE: {
    TOOLTIP: (percentile: number) => `Percentile ${percentile} vs tournament average`,
    LEVELS: {
      HIGH: "HIGH (71-100%)",
      MEDIUM: "MEDIUM (51-70%)",
      LOW: "LOW (0-50%)",
    },
    BAR: {
      HEIGHT_MOBILE: "h-3",
      HEIGHT_DESKTOP: "sm:h-2.5",
      BACKGROUND_COLOR: "bg-gray-100 dark:bg-gray-800",
      SHADOW: "shadow-inner",
      TEXT_SHADOW: "drop-shadow-sm",
      TRANSITION: "transition-all duration-700 ease-out",
      SHADOW_SM: "shadow-sm",
      CONTAINER_CLASSES: "w-full rounded-full relative overflow-hidden",
      BAR_CLASSES: "rounded-full",
      TEXT_CLASSES: "absolute right-1 sm:right-2 top-1/2 -translate-y-1/2 text-xs font-medium",
    },
  },
  CATEGORIES: {
    GOALS: "Goals",
    PASSING: "Passing",
    DEFENSE: "Defense",
    PHYSICAL: "Physical",
    SHOOTING: "Shooting",
    AERIAL: "Aerial",
    CROSSING: "Crossing",
    DRIBBLING: "Dribbling",
    POSSESSION: "Possession",
    DUELS: "Duels",
  },
  METRICS: {
    GOALS_SCORED: "Goals Scored",
    SHOT_ACCURACY: "Shot Accuracy",
    PASS_ACCURACY: "Pass Accuracy",
    KEY_PASSES: "Key Passes",
    TACKLES_WON: "Tackles Won",
    INTERCEPTIONS: "Interceptions",
    DISTANCE_COVERED: "Distance Covered",
    DUELS_WON: "Duels Won",
    SHOTS_ON_TARGET: "Shots on Target",
    SHOT_POWER: "Shot Power",
    ASSISTS: "Assists",
    CLEARANCES: "Clearances",
  },
  METRIC_FORMATTER: {
    REPLACE_UNDERSCORES: (metric: string) => metric.replace(/_/g, ' '),
  },
  LOADING: {
    SKELETON_TITLE: "Loading...",
    SKELETON_CARDS: "Loading statistics...",
    SKELETON_COUNT: 3,
    SKELETON_HEIGHT: "h-20",
    SKELETON_WIDTH: "w-full",
    SKELETON_TITLE_HEIGHT: "h-6",
    SKELETON_TITLE_WIDTH: "w-48",
    SKELETON_CONTAINER: "space-y-4",
  },
  ERRORS: {
    NETWORK_ERROR: "Network error. Please try again.",
    VALIDATION_ERROR: "Invalid data received.",
    UNKNOWN_ERROR: "An unexpected error occurred.",
    CONTAINER_CLASSES: "p-6",
    MESSAGE_CLASSES: "text-destructive",
  },
  HOOK: {
    INITIAL_STATE: {
      STATS: [],
      LOADING: true,
      ERROR: null
    }
  },
} as const

export type PlayerStatsTexts = typeof PLAYER_STATS_TEXTS
